### ISSUE TITLE
Device a verbosity configuration

### ISSUE THREAD

**Issue by PabloCorcho** [pykoala/pykoala#421]
Different parts of the code have their own method for printing according to a verbosity argument. In some cases it corresponds to an attribute of an object, and in other cases it is just another argument that is passed to the methods. There should be a unique approach to declare verbosity in the code and potentially it should affect to all methods and classes.

**Comment by paranoya** [comment]
I guess we should not reinvent the wheel:
<https://docs.python.org/3/howto/logging.html#logging-basic-tutorial>
