### ISSUE TITLE
Uncomment a line in sky.py to see the telluric plots

### ISSUE THREAD

**Issue by angelrls** [pykoala/pykoala#435]
The other change I need in the code is again in file sky.py         

I can't get the plots of the telluric correction showing in the screen unless line 696 within task plot_correction() is uncommented:

plt.show()

That is the second of the 2 only changes I need in the main code for the rss.koala tasks to work.

The rest works without problems.

Thanks.

**Comment by PabloCorcho** [comment]
This is fixed in #438. I have included a boolean `plot` argument for showing the plot. By default the figure is closed (it can always be reopened outside the function using `plt.figure(fig)`) as we do not want to keep the plots in memory when reducing a significant amount of data.
