### ISSUE TITLE
How to check documentation remotely (plus current errors)

### ISSUE THREAD

**Issue by miguelglezb** [pykoala/pykoala#440]
For this, I use the sphinx version that comes in `requirements.txt`, since sphinx can be wildly different between versions. We can change that eventually if it fixes things.

To create the documentation locally, and check docstring immediately without the need to do a PR, go in the koala directory and use:

```bash
cd docs
rm -rf _build
make html
firefox _build/html/index.html
```

If you use another browser, replace firefox for it.

In the lastest main version, I am getting this issues:

```
Parameters #TODO
----------
/home/mbolivar/naive_user/koala/src/pykoala/rss.py:docstring of pykoala.rss.RSS:30: ERROR: Unexpected indentation.
/home/mbolivar/naive_user/koala/docs/index.rst:7: WARNING: Title underline too short.

Welcome to PyKoala's documentation!
=================================
/home/mbolivar/naive_user/koala/src/pykoala/corrections/flux_calibration.py:docstring of pykoala.corrections.flux_calibration.FluxCalibration.auto:27: ERROR: Unexpected indentation.
/home/mbolivar/naive_user/koala/src/pykoala/corrections/flux_calibration.py:docstring of pykoala.corrections.flux_calibration.FluxCalibration.auto:1: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/mbolivar/naive_user/koala/src/pykoala/corrections/flux_calibration.py:docstring of pykoala.corrections.flux_calibration.FluxCalibration.auto:1: WARNING: Inline strong start-string without end-string.
/home/mbolivar/naive_user/koala/src/pykoala/corrections/flux_calibration.py:docstring of pykoala.corrections.flux_calibration.FluxCalibration.get_response_curve:11: ERROR: Unexpected indentation.
```
I want to work on them, but I'd like to wait until PR #437 is finished to push anything else.

**Comment by PabloCorcho** [comment]
Thanks @miguelglezb. Do not worry about the documentation of this module. I think your help is more useful on the tutorials side, giving a hand to @angelrls  (I think there is still not a tutorial that includes the cubing part). In that module there are many missing docstrings and I have to update them. In fact, I plan to review and update almost all the modules during the next few days so the documentation is almost complete before the workshop.

**Comment by miguelglezb** [comment]
Thanks @PabloCorcho! I mostly made this issue to show everyone how to check if the docstrings are showing in the html files locally. This will save time by allowing to check changes without the need to pull request them first.

**Comment by PabloCorcho** [comment]
I have moved the contents of this ticket to [a wiki page](https://github.com/pykoala/pykoala/wiki/Checking-documentation). We can write extensive instructions for developers there. Have a look an make the changes that you consider appropriate. After that, close this ticket.
