### ISSUE TITLE
vprint functionality 

### ISSUE THREAD

**Issue by miguelglezb** [pykoala/pykoala#449]
`vprint` is an unbound function, but in class `SkyFromObject` is used as an attribute. This is causing an issue when running `py.test` and showing a warning in `pylance`. While the execution in VS code does not show issues, the function should not be run as attribute in this case anyway since it is an external function in `sky.py`. I recommend checking its usage in other parts of the code.

Moreover, this function is giving a keyerror when run:
```python
KeyError: 'verbose'
```

This issue has been fixed in PR #445

**Comment by paranoya** [comment]
Eventually, `vprint` will disappear. Closed in favour of <https://github.com/pykoala/pykoala/issues/421>
